use std::path::Path;

use crate::{Entry, Scope};

pub(crate) const INDEX_FILE: &str = "INDEX.md";

pub(crate) fn render(scope: Scope, entries: &[Entry]) -> String {
    let title = match scope {
        Scope::User => "User Memory Index",
        Scope::Project => "Project Memory Index",
    };
    let mut output =
        format!("<!-- Generated by h-memory. Do not edit directly. -->\n\n# {title}\n");

    for entry in entries {
        output.push('\n');
        output.push_str(&line(entry));
    }

    output.push('\n');
    output
}

pub(crate) fn snapshot(
    scope: Scope,
    index_path: &Path,
    entries: &[Entry],
    budget: usize,
) -> String {
    let title = match scope {
        Scope::User => "User memory",
        Scope::Project => "Current project memory",
    };
    let header = format!("## {title}\n\nIndex: {}\n\n", index_path.display());
    let mut output = header;
    let marker_reserve = 160_usize;
    let mut shown = 0_usize;
    let mut prioritized = entries.iter().collect::<Vec<_>>();

    prioritized.sort_by(|left, right| {
        right
            .updated_at
            .cmp(&left.updated_at)
            .then_with(|| left.id.cmp(&right.id))
    });

    for entry in prioritized {
        let next = format!("{}\n", line(entry));
        if output.len() + next.len() + marker_reserve > budget {
            break;
        }

        output.push_str(&next);
        shown += 1;
    }

    if shown == 0 {
        output.push_str("No memory topics have been recorded in this scope.\n");
    }

    if shown < entries.len() {
        output.push_str(&format!(
            "\nShowing {shown} of {} topics. Use `search_memory` to find omitted topics.\n",
            entries.len()
        ));
    }

    output
}

fn line(entry: &Entry) -> String {
    format!(
        "- [{}](topics/{}.md) — {}",
        escape(&entry.title),
        entry.id,
        entry.summary
    )
}

fn escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use chrono::{TimeDelta, Utc};

    use super::*;

    fn entry(id: &str, updated_at: chrono::DateTime<Utc>) -> Entry {
        Entry {
            id: id.to_owned(),
            title: id.to_owned(),
            summary: format!("Summary for {id}."),
            keywords: Vec::new(),
            content: "Content".to_owned(),
            updated_at,
            scope: Scope::Project,
            path: PathBuf::from(format!("topics/{id}.md")),
            revision: "revision".to_owned(),
        }
    }

    #[test]
    fn snapshot_prioritizes_recently_updated_topics() {
        let now = Utc::now();
        let entries = vec![
            entry("alphabetically-first", now - TimeDelta::days(1)),
            entry("recently-updated", now),
        ];
        let snapshot = snapshot(Scope::Project, Path::new("INDEX.md"), &entries, 4_096);
        let recent = snapshot.find("recently-updated").unwrap();
        let older = snapshot.find("alphabetically-first").unwrap();

        assert!(recent < older);
    }
}
